// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeHSG-cearCEwcEeAjoAtNP9bYApD4u0o',
    appId: '1:880245869181:web:e94dd3438725d9a4f1ff14',
    messagingSenderId: '880245869181',
    projectId: 'sonemathappdatabase',
    authDomain: 'sonemathappdatabase.firebaseapp.com',
    storageBucket: 'sonemathappdatabase.appspot.com',
    measurementId: 'G-KRQPVQX257',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKTVTorB4Fsto3ujSKOBhVdHt5NecQUAg',
    appId: '1:880245869181:android:ff23f31facb98540f1ff14',
    messagingSenderId: '880245869181',
    projectId: 'sonemathappdatabase',
    storageBucket: 'sonemathappdatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9GsGPR6CiQ4GEy7XsvFjGMETP6_nxdc',
    appId: '1:880245869181:ios:2cc9d59b02c02f32f1ff14',
    messagingSenderId: '880245869181',
    projectId: 'sonemathappdatabase',
    storageBucket: 'sonemathappdatabase.appspot.com',
    iosBundleId: 'com.example.emathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv9GsGPR6CiQ4GEy7XsvFjGMETP6_nxdc',
    appId: '1:880245869181:ios:2cc9d59b02c02f32f1ff14',
    messagingSenderId: '880245869181',
    projectId: 'sonemathappdatabase',
    storageBucket: 'sonemathappdatabase.appspot.com',
    iosBundleId: 'com.example.emathApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeHSG-cearCEwcEeAjoAtNP9bYApD4u0o',
    appId: '1:880245869181:web:3999aa35d45a965cf1ff14',
    messagingSenderId: '880245869181',
    projectId: 'sonemathappdatabase',
    authDomain: 'sonemathappdatabase.firebaseapp.com',
    storageBucket: 'sonemathappdatabase.appspot.com',
    measurementId: 'G-GETG9G40BD',
  );
}
